# Generated by Django 4.0.4 on 2022-06-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_alter_block_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='indents',
            field=models.BooleanField(default=True, verbose_name='Отступы по бокам'),
        ),
        migrations.AlterField(
            model_name='block',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Ширина экрана разделяется на 12 частей. В сумме с остальными блоками ширина не должна быть больше 12. Если оставить 0, ширина будет вычислена автоматически.', null=True, verbose_name='Ширина блока'),
        ),
    ]
