# Generated by Django 4.0.4 on 2022-06-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0017_alter_column_created_at_alter_module_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='published',
        ),
        migrations.RemoveField(
            model_name='column',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='published',
        ),
        migrations.RemoveField(
            model_name='section',
            name='published_at',
        ),
    ]
