# Generated by Django 4.0.4 on 2022-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0022_module_menu_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='menu_style',
            field=models.CharField(choices=[('horizontal_blocks', 'Горизонтальное меню (блоки)'), ('vertical_with_submenus', 'Вертикальное меню (с подпунктами)'), ('vertical_without_submenus', 'Вертикальное меню (без подпунктов)')], default='horizontal_blocks', max_length=64, verbose_name='Макет меню'),
        ),
    ]
