# Generated by Django 4.0.5 on 2022-07-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0039_rename_is_published_menu_published'),
        ('grid', '0029_rename_feed_content_modulecontent_feed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='content_type',
            field=models.CharField(choices=[('', '---'), ('menu', 'Меню'), ('post', 'Пост'), ('feed', 'Лента постов')], default='', max_length=64, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Меню'),
        ),
    ]
