# Generated by Django 4.0.5 on 2022-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0031_module_invert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['column', 'order'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='feed_num_columns',
            field=models.PositiveSmallIntegerField(choices=[('1', '1 колонка'), ('2', '2 колонки'), ('3', '3 колонки'), ('4', '4 колонки')], default='2', verbose_name='Количество колонок'),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='feed_style',
            field=models.CharField(choices=[('compact_feed', 'Список постов (только заголовки)'), ('blocks', 'Посты в виде блоков'), ('slider', 'Слайдер постов')], default='compact_feed', max_length=64, verbose_name='Макет ленты постов'),
        ),
    ]
