# Generated by Django 4.0.5 on 2022-07-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0033_modulecontent_feed_count_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecontent',
            old_name='feed_count_posts',
            new_name='feed_count_objects',
        ),
    ]
