# Generated by Django 4.0.5 on 2022-07-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0035_modulecontent_feed_readmore'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecontent',
            name='feed_object_sorting',
            field=models.CharField(choices=[('horizontal', 'Построчно'), ('vertical', 'По колонкам')], default='horizontal', max_length=16, verbose_name='Сортировка постов'),
        ),
        migrations.AlterField(
            model_name='modulecontent',
            name='feed_readmore',
            field=models.BooleanField(default=True, verbose_name='Отображать кнопку "Читать больше"'),
        ),
    ]
