# Generated by Django 4.0.5 on 2022-07-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0037_remove_modulecontent_feed_object_sorting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecontent',
            old_name='feeв_sort_direction',
            new_name='feed_sort_direction',
        ),
    ]
