# Generated by Django 4.0.5 on 2022-07-19 02:24

from django.db import migrations, models
from grid.models import ModuleContent
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0041_widget'),
    ]

    def gen_uuid_modulecontent(apps, schema_editor):
        for row in ModuleContent.objects.all():
            row.uid = uuid.uuid4()
            row.save()
    
    operations = [
        migrations.AddField(
            model_name='modulecontent',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(gen_uuid_modulecontent),
        migrations.AlterField(
            model_name="modulecontent",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
