# Generated by Django 4.0.5 on 2022-07-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0040_remove_menu_is_fixed_menu_megamenu'),
        ('grid', '0042_modulecontent_uid_widget_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecontent',
            old_name='feed',
            new_name='feed_content',
        ),
        migrations.RenameField(
            model_name='modulecontent',
            old_name='post',
            new_name='post_content',
        ),
        migrations.RemoveField(
            model_name='modulecontent',
            name='menu',
        ),
        migrations.AddField(
            model_name='modulecontent',
            name='menu_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.menu', verbose_name='Меню'),
        ),
    ]
