# Generated by Django 4.0.5 on 2022-07-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0047_modulecontent_show_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulecontent',
            name='show_title',
        ),
    ]
