# Generated by Django 4.0.5 on 2022-07-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0051_alter_modulecontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='content_type',
            field=models.CharField(choices=[('', '---'), ('post', 'Пост'), ('feed', 'Лента постов'), ('menu', 'Меню')], default='', max_length=64, verbose_name='Тип контента'),
        ),
    ]
