# Generated by Django 4.0.6 on 2022-07-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0052_alter_modulecontent_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleContent',
        ),
    ]
