# Generated by Django 4.0.6 on 2022-07-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_contentlayout_delete_extracontent'),
        ('grid', '0053_delete_modulecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleContent',
            fields=[
                ('contentlayout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.contentlayout')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['order'],
            },
            bases=('content.contentlayout', models.Model),
        ),
    ]
