# Generated by Django 4.0.4 on 2022-05-07 11:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0030_alter_menu_debug_info'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Привязка к меню'),
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('menu', models.ManyToManyField(to='menus.menu', verbose_name='Привязка к меню')),
            ],
        ),
    ]
