# Generated by Django 4.0.4 on 2022-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_feed_alias_remove_post_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='alias',
            field=models.SlugField(blank=True, default='', help_text="Краткое название транслитом через тире (пример: 'kratkoe-nazvanie-translitom'). Чем короче тем лучше. Для автоматического заполнения - оставьте пустым.", max_length=1000, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='alias',
            field=models.SlugField(blank=True, default='', help_text="Краткое название транслитом через тире (пример: 'kratkoe-nazvanie-translitom'). Чем короче тем лучше. Для автоматического заполнения - оставьте пустым.", max_length=1000),
        ),
    ]
