# Generated by Django 4.0.6 on 2022-08-01 06:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracontent',
            options={'ordering': ['order'], 'verbose_name': 'дополнительный контент', 'verbose_name_plural': 'дополнительный контент'},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='count_objects',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='num_columns',
        ),
        migrations.AlterField(
            model_name='extracontent',
            name='position',
            field=models.CharField(choices=[('content', 'Контент'), ('right', 'Справа'), ('left', 'Слева'), ('bottom', 'Внизу'), ('top', 'Сверху'), ('stacked', 'Под постом (В виде ленты)')], default='content', max_length=64, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
