# Generated by Django 4.0.6 on 2022-08-25 08:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tag_taggedpost_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='test',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
