# Generated by Django 4.0.4 on 2022-05-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0030_alter_menu_debug_info'),
        ('content', '0002_alter_post_menu_postcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='Feed',
        ),
    ]
