# Generated by Django 4.0.6 on 2022-08-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_parent_feed_show_childs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_position',
            field=models.CharField(choices=[('left', 'Слева'), ('stretch', 'Растянуть'), ('right', 'Справа'), ('hide', 'Скрыть')], default='left', max_length=64, verbose_name='Расположение изображения'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.feed', verbose_name='Родительская лента'),
        ),
    ]
