# Generated by Django 4.0.6 on 2022-08-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_tag_test_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
