# Generated by Django 4.0.4 on 2022-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='feed',
            field=models.ManyToManyField(blank=True, to='content.feed', verbose_name='Категория'),
        ),
    ]
