# Generated by Django 4.0.6 on 2022-08-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_tag_options_remove_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlayout',
            name='tagcloud_style',
            field=models.CharField(choices=[('classic_cloud', 'В виде облака'), ('structured_cloud', 'В виде таблицы')], default='classic_cloud', max_length=64, verbose_name='Макет облака тегов'),
        ),
        migrations.AlterField(
            model_name='contentlayout',
            name='content_type',
            field=models.CharField(choices=[('', '---'), ('post', 'Пост'), ('feed', 'Лента постов'), ('menu', 'Меню'), ('tagcloud', 'Облако тегов')], default='', max_length=64, verbose_name='Тип контента'),
        ),
    ]
