# Generated by Django 4.0.6 on 2022-08-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
