# Generated by Django 4.0.4 on 2022-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_feed_alias_feed_title_post_alias_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
