# Generated by Django 4.0.4 on 2022-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='alias',
            field=models.SlugField(blank=True, default='', help_text="Краткое название транслитом через тире (пример: 'kratkoe-nazvanie-translitom'). Чем короче тем лучше. Для автоматического заполнения - оставьте пустым.", max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='alias',
            field=models.SlugField(blank=True, default='', help_text="Краткое название транслитом через тире (пример: 'kratkoe-nazvanie-translitom'). Чем короче тем лучше. Для автоматического заполнения - оставьте пустым.", max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='feed',
            field=models.ManyToManyField(blank=True, to='content.feed', verbose_name='Лента'),
        ),
    ]
