# Generated by Django 4.0.4 on 2022-05-22 12:22

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_feed_alias_alter_post_alias_alter_post_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to=content.models.attachment_upload_location, verbose_name='Вложение'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='feed',
        ),
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.feed', verbose_name='Лента постов'),
        ),
    ]
