# Generated by Django 4.0.4 on 2022-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_rename_attachment_attachment_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Расширение файла'),
        ),
    ]
