# Generated by Django 4.0.4 on 2022-05-25 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_feed_created_at_feed_published_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
