# Generated by Django 4.0.4 on 2022-05-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_feed_hits_post_hits_alter_feed_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
