# Generated by Django 4.0.4 on 2022-05-29 08:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_rename_date_publish_attachment_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
