# Generated by Django 4.0.4 on 2022-06-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_post_intro_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
    ]
