# Generated by Django 4.0.5 on 2022-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': 'Лента постов', 'verbose_name_plural': 'Ленты постов'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
