# Generated by Django 4.0.5 on 2022-07-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_alter_feed_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
