# Generated by Django 4.0.5 on 2022-07-18 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0040_remove_menu_is_fixed_menu_megamenu'),
        ('content', '0030_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='menu',
        ),
        migrations.AddField(
            model_name='feed',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Привязка к меню'),
        ),
    ]
