# Generated by Django 4.0.5 on 2022-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_alter_post_feed_alter_post_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='count_objects',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Количество выводимых постов'),
        ),
        migrations.AddField(
            model_name='feed',
            name='num_columns',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 колонка'), (2, '2 колонки'), (3, '3 колонки'), (4, '4 колонки')], default=1, verbose_name='Количество колонок'),
        ),
    ]
