# Generated by Django 4.0.5 on 2022-07-23 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0040_remove_menu_is_fixed_menu_megamenu'),
        ('content', '0033_feed_count_objects_feed_num_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='menu',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_type', models.CharField(choices=[('', '---'), ('menu', 'Меню'), ('post', 'Пост'), ('feed', 'Лента постов')], default='', max_length=64, verbose_name='Тип контента')),
                ('feed_style', models.CharField(choices=[('compact_feed', 'Список постов (только заголовки)'), ('blocks', 'Посты в виде блоков'), ('slider', 'Слайдер постов')], default='compact_feed', max_length=64, verbose_name='Макет ленты постов')),
                ('feed_num_columns', models.PositiveSmallIntegerField(choices=[(1, '1 колонка'), (2, '2 колонки'), (3, '3 колонки'), (4, '4 колонки')], default=2, verbose_name='Количество колонок')),
                ('feed_count_items', models.PositiveSmallIntegerField(default=6, verbose_name='Количество выводимых постов')),
                ('feed_readmore', models.BooleanField(default=True, verbose_name='Отображать кнопку "Читать больше"')),
                ('feed_sort_direction', models.CharField(choices=[('horizontal', 'Построчно'), ('vertical', 'По колонкам')], default='horizontal', max_length=16, verbose_name='Направление сортировки')),
                ('menu_style', models.CharField(choices=[('horizontal_blocks', 'Горизонтальное меню (блоки)'), ('vertical_with_submenus', 'Вертикальное меню (с дочерними меню)'), ('vertical_without_submenus', 'Вертикальное меню (без дочерних меню)')], default='horizontal_blocks', max_length=64, verbose_name='Макет меню')),
                ('position', models.CharField(choices=[('content', 'Контент'), ('right', 'Справа'), ('left', 'Слева'), ('bottom', 'Внизу'), ('top', 'Сверху'), ('stacked', 'Под постом (В виде ленты)'), ('tab', 'Вкладка')], default='content', max_length=64, verbose_name='Расположение')),
                ('content_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.feed', verbose_name='Лента постов')),
                ('content_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.menu', verbose_name='Меню')),
                ('content_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.post', verbose_name='Пост')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Привязка к меню')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['order'],
            },
        ),
    ]
