# Generated by Django 4.0.5 on 2022-07-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_remove_feed_menu_remove_post_menu_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='position',
            field=models.CharField(choices=[('content', 'Контент'), ('right', 'Справа'), ('left', 'Слева'), ('bottom', 'Внизу'), ('top', 'Сверху'), ('stacked', 'Под постом (В виде ленты)')], default='content', max_length=64, verbose_name='Расположение'),
        ),
    ]
