# Generated by Django 4.0.5 on 2022-07-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_content_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='feed_style',
            field=models.CharField(choices=[('compact_feed', 'Список постов (только заголовки)'), ('blocks', 'Посты в виде блоков (без изображений)'), ('blocks_with_images_left', 'Посты в виде блоков (изображения слева'), ('blocks_with_images_top', 'Посты в виде блоков (изображения сверху'), ('slider', 'Слайдер постов')], default='compact_feed', max_length=64, verbose_name='Макет ленты постов'),
        ),
        migrations.AlterField(
            model_name='content',
            name='show_title',
            field=models.BooleanField(default=False, verbose_name='Отображать заголовок'),
        ),
    ]
