# Generated by Django 4.0.5 on 2022-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_extracontent_remove_feed_menu_remove_post_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontent',
            name='content_type',
            field=models.CharField(choices=[('', '---'), ('post', 'Пост'), ('feed', 'Лента постов')], default='', max_length=64, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='extracontent',
            name='position',
            field=models.CharField(choices=[('right', 'Справа'), ('left', 'Слева'), ('bottom', 'Внизу'), ('top', 'Сверху'), ('stacked', 'Под постом (В виде ленты)')], default='right', max_length=64, verbose_name='Расположение'),
        ),
    ]
