# Generated by Django 4.0.4 on 2022-04-18 09:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
