# Generated by Django 4.0.4 on 2022-04-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='alias',
            field=models.CharField(help_text="Краткое название транслитом через тире (пример: 'kratkoe-nazvanie-menu-na-translite'", max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(help_text='Краткое описание содержимого меню', verbose_name='Описание:'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Родитель:'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Привязка к меню:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок:'),
        ),
    ]
