# Generated by Django 4.0.4 on 2022-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_menu_is_fixed_alter_menu_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Если отмечено - дочерние пункты меню будут раскрываться, если нет - не будут.', verbose_name='Раскрывать дочерние пункты меню?'),
        ),
    ]
