# Generated by Django 4.0.4 on 2022-04-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_alter_menu_description_alter_menu_is_fixed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
