# Generated by Django 4.0.4 on 2022-04-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0019_alter_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
