# Generated by Django 4.0.4 on 2022-05-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0026_menu_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
