# Generated by Django 4.0.4 on 2022-05-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0029_alter_menu_options_menu_debug_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='debug_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
