# Generated by Django 4.0.4 on 2022-05-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0030_alter_menu_debug_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_path',
            field=models.CharField(blank=True, default='hz', max_length=1000, null=True),
        ),
    ]
