# Generated by Django 4.0.4 on 2022-05-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0032_remove_menu_url_path_menu_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='url',
            new_name='url_path',
        ),
    ]
