# Generated by Django 4.0.4 on 2022-06-06 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0034_rename_url_path_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы')),
                ('background', models.CharField(default='ffffff', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы')),
                ('background', models.CharField(default='ffffff', max_length=6)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.row', verbose_name='Горизонтальная позиция')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
