# Generated by Django 4.0.5 on 2022-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0039_rename_is_published_menu_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_fixed',
        ),
        migrations.AddField(
            model_name='menu',
            name='megamenu',
            field=models.BooleanField(default=False, help_text='Если отмечено, меню будет выпадать шириной во весь экран', verbose_name='Мегаменю'),
        ),
    ]
