# Generated by Django 4.0.5 on 2022-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0040_remove_menu_is_fixed_menu_megamenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
    ]
