# Generated by Django 4.0.4 on 2022-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0025_alter_menu_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
