# Generated by Django 4.0.4 on 2022-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0027_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
