# Generated by Django 4.0.4 on 2022-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0028_menu_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['parent_id', 'order']},
        ),
        migrations.AddField(
            model_name='menu',
            name='debug_info',
            field=models.TextField(default=''),
        ),
    ]
