# Generated by Django 4.0.4 on 2022-05-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0031_menu_url_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_path',
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
