# Generated by Django 4.0.4 on 2022-05-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0033_rename_url_menu_url_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='url_path',
            new_name='url',
        ),
    ]
