# Generated by Django 4.0.4 on 2022-06-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0035_row_col'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Col',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
