# Generated by Django 4.0.4 on 2022-06-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0036_delete_col_delete_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='list_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
