# Generated by Django 4.0.4 on 2022-06-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0037_menu_list_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['list_order'], 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
