# Generated by Django 4.0.4 on 2022-06-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0038_alter_menu_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_published',
            new_name='published',
        ),
    ]
