# Generated by Django 4.0.6 on 2022-08-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='taggedpost',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TaggedPost',
        ),
    ]
