# Generated by Django 4.0.4 on 2022-06-06 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы')),
                ('background', models.CharField(default='ffffff', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы')),
                ('background', models.CharField(default='ffffff', max_length=6)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_settings.section', verbose_name='Секция')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
