# Generated by Django 4.0.4 on 2022-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='block',
            name='classes',
            field=models.CharField(blank=True, help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы'),
        ),
        migrations.AlterField(
            model_name='section',
            name='classes',
            field=models.CharField(blank=True, help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы'),
        ),
    ]
