# Generated by Django 4.0.4 on 2022-06-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_block_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
    ]
