# Generated by Django 4.0.4 on 2022-06-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_block_centrize'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='Заголовок'),
        ),
    ]
