# Generated by Django 4.0.4 on 2022-06-08 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_module_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='background',
        ),
        migrations.RemoveField(
            model_name='module',
            name='background',
        ),
        migrations.RemoveField(
            model_name='section',
            name='background',
        ),
        migrations.AddField(
            model_name='column',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='column',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='column',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='column',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='module',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='module',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='section',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='section',
            name='published_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
