# Generated by Django 4.0.4 on 2022-06-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_feed_options_alter_post_options'),
        ('menus', '0038_alter_menu_options'),
        ('site_settings', '0019_alter_module_options_module_show_on_every_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.feed', verbose_name='Лента постов'),
        ),
        migrations.AddField(
            model_name='module',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.post', verbose_name='Пост'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='menu',
        ),
        migrations.AddField(
            model_name='module',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Меню'),
        ),
    ]
