# Generated by Django 4.0.4 on 2022-06-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0038_alter_menu_options'),
        ('site_settings', '0020_module_feed_module_post_remove_module_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='feed',
            new_name='feed_content',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='post',
            new_name='post_content',
        ),
        migrations.AddField(
            model_name='module',
            name='menu_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_content', to='menus.menu', verbose_name='Меню'),
        ),
        migrations.RemoveField(
            model_name='module',
            name='menu',
        ),
        migrations.AddField(
            model_name='module',
            name='menu',
            field=models.ManyToManyField(to='menus.menu', verbose_name='Привязка к меню'),
        ),
    ]
