# Generated by Django 4.0.4 on 2022-06-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0021_rename_feed_module_feed_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='menu_style',
            field=models.CharField(choices=[('horizontal_blocks', 'Горизонтальное меню (блоки)'), ('vertical', 'Вертикальное меню')], default='horizontal_blocks', max_length=64, verbose_name='Макет меню'),
        ),
    ]
