# Generated by Django 4.0.4 on 2022-06-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0024_module_feed_style_alter_module_menu_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='feed_style',
            field=models.CharField(choices=[('compact_feed', 'Лента постов (только заголовки)'), ('slider', 'Слайдер постов')], default='compact_feed', max_length=64, verbose_name='Макет ленты постов'),
        ),
    ]
