# Generated by Django 4.0.4 on 2022-06-29 03:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0026_module_post_html_module_pre_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='post_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Текст в конце модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pre_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Текст в начале модуля'),
        ),
    ]
