# Generated by Django 4.0.4 on 2022-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_alter_section_options_block_name_block_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='order',
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
    ]
