# Generated by Django 4.0.4 on 2022-06-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_alter_block_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
    ]
