# Generated by Django 4.0.4 on 2022-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AddField(
            model_name='block',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Ширина экрана разделяется на 12 частей. Допускается использовать любую ширину до 12.         В сумме с остальными блоками ширина не должна быть больше 12', null=True, verbose_name='Ширина блока'),
        ),
    ]
