# Generated by Django 4.0.4 on 2022-06-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0009_block_standart_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='centrize',
            field=models.BooleanField(default=False, verbose_name='Центрировать содержимое'),
        ),
    ]
