# Generated by Django 4.0.4 on 2022-06-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0011_block_show_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('classes', models.CharField(blank=True, help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы')),
                ('background', models.CharField(default='ffffff', max_length=6)),
                ('width', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Ширина экрана разделяется на 12 частей. В сумме с остальными блоками ширина не должна быть больше 12. Если оставить 0, ширина будет вычислена автоматически.', null=True, verbose_name='Ширина блока')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Колонка',
                'verbose_name_plural': 'Колонки',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
