# Generated by Django 4.0.4 on 2022-06-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0013_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('classes', models.CharField(blank=True, help_text='Можно использовать bootstrap классы.', max_length=256, verbose_name='CSS классы')),
                ('background', models.CharField(default='ffffff', max_length=6)),
                ('show_title', models.BooleanField(default=True, verbose_name='Заголовок')),
                ('standart_design', models.BooleanField(default=True, verbose_name='Оформление по умолчанию')),
                ('centrize', models.BooleanField(default=False, verbose_name='Центрировать содержимое')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['section', 'order'], 'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.AddField(
            model_name='module',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.column', verbose_name='Позиция'),
        ),
    ]
