# Generated by Django 4.0.4 on 2022-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0023_alter_module_menu_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='feed_style',
            field=models.CharField(choices=[('compact_feed', 'Лента постов (только заголовки)'), ('slider', 'Слайдер постов')], default='compact_feed', max_length=64, verbose_name='Макет ленты'),
        ),
        migrations.AlterField(
            model_name='module',
            name='menu_style',
            field=models.CharField(choices=[('horizontal_blocks', 'Горизонтальное меню (блоки)'), ('vertical_with_submenus', 'Вертикальное меню (с дочерними меню)'), ('vertical_without_submenus', 'Вертикальное меню (без дочерних меню)')], default='horizontal_blocks', max_length=64, verbose_name='Макет меню'),
        ),
    ]
