# Generated by Django 4.0.4 on 2022-06-24 03:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0025_alter_module_feed_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='post_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текст в конце модуля'),
        ),
        migrations.AddField(
            model_name='module',
            name='pre_html',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текст в начале модуля'),
        ),
    ]
