# Generated by Django 4.0.5 on 2022-07-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0030_alter_modulecontent_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='invert',
            field=models.BooleanField(default=False, help_text='Модуль будет привязан ко всем меню, кроме отмеченных.', verbose_name='Инвертировать выбор меню'),
        ),
    ]
