# Generated by Django 4.0.5 on 2022-07-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0038_rename_feeв_sort_direction_modulecontent_feed_sort_direction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleContent',
        ),
    ]
