# Generated by Django 4.0.5 on 2022-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0049_alter_modulecontent_feed_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='feed_style',
            field=models.CharField(choices=[('feed', 'Список постов'), ('compact_feed', 'Список постов (только заголовки)'), ('blocks', 'Посты в виде блоков (без изображений)'), ('blocks_with_images_left', 'Посты в виде блоков (изображения слева)'), ('blocks_with_images_top', 'Посты в виде блоков (изображения сверху)'), ('slider', 'Слайдер постов')], default='feed', max_length=64, verbose_name='Макет ленты постов'),
        ),
    ]
