# Generated by Django 4.0.4 on 2022-05-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='post',
            name='alias',
        ),
    ]
