# Generated by Django 4.0.4 on 2022-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_alias_post_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.ManyToManyField(blank=True, null=True, to='content.feed', verbose_name='Категория'),
        ),
    ]
