# Generated by Django 4.0.4 on 2022-05-22 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_attachment_attachment_remove_post_feed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='date_publish',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
