# Generated by Django 4.0.4 on 2022-05-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_attachment_date_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='attached_file',
        ),
    ]
