# Generated by Django 4.0.4 on 2022-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_attachment_id_alter_attachment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во загрузок'),
        ),
    ]
