# Generated by Django 4.0.4 on 2022-05-25 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_attachment_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='feed',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
