# Generated by Django 4.0.4 on 2022-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение поста'),
        ),
    ]
