# Generated by Django 4.0.5 on 2022-07-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0040_remove_menu_is_fixed_menu_megamenu'),
        ('content', '0031_remove_feed_menu_feed_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.feed', verbose_name='Лента постов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Привязка к меню'),
        ),
    ]
