# Generated by Django 4.0.5 on 2022-07-28 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0040_remove_menu_is_fixed_menu_megamenu'),
        ('content', '0037_alter_content_feed_style_alter_content_show_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительный контент', 'verbose_name_plural': 'Дополнительный контент'},
        ),
        migrations.AddField(
            model_name='feed',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Привязка к меню'),
        ),
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Привязка к меню'),
        ),
        migrations.AlterField(
            model_name='content',
            name='feed_style',
            field=models.CharField(choices=[('feed', 'Список постов'), ('compact_feed', 'Список постов (только заголовки)'), ('blocks', 'Посты в виде блоков (без изображений)'), ('blocks_with_images_left', 'Посты в виде блоков (изображения слева)'), ('blocks_with_images_top', 'Посты в виде блоков (изображения сверху)'), ('slider', 'Слайдер постов')], default='feed', max_length=64, verbose_name='Макет ленты постов'),
        ),
        migrations.AlterField(
            model_name='content',
            name='position',
            field=models.CharField(choices=[('right', 'Справа'), ('left', 'Слева'), ('bottom', 'Внизу'), ('top', 'Сверху'), ('stacked', 'Под постом (В виде ленты)')], default='right', max_length=64, verbose_name='Расположение'),
        ),
    ]
