# Generated by Django 4.0.6 on 2022-07-30 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0041_alter_menu_order'),
        ('content', '0041_alter_extracontent_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feed_style', models.CharField(choices=[('feed', 'Список постов'), ('compact_feed', 'Список постов (только заголовки)'), ('blocks', 'Посты в виде блоков (без изображений)'), ('blocks_with_images_left', 'Посты в виде блоков (изображения слева)'), ('blocks_with_images_top', 'Посты в виде блоков (изображения сверху)'), ('slider', 'Слайдер постов')], default='feed', max_length=64, verbose_name='Макет ленты постов')),
                ('feed_num_columns', models.PositiveSmallIntegerField(choices=[(1, '1 колонка'), (2, '2 колонки'), (3, '3 колонки'), (4, '4 колонки')], default=2, verbose_name='Количество колонок')),
                ('feed_count_items', models.PositiveSmallIntegerField(default=6, verbose_name='Количество выводимых постов')),
                ('feed_readmore', models.BooleanField(default=True, verbose_name='Отображать кнопку "Читать больше"')),
                ('feed_sort_direction', models.CharField(choices=[('horizontal', 'Построчно'), ('vertical', 'По колонкам')], default='horizontal', max_length=16, verbose_name='Направление сортировки')),
                ('content_type', models.CharField(choices=[('', '---'), ('post', 'Пост'), ('feed', 'Лента постов'), ('menu', 'Меню')], default='', max_length=64, verbose_name='Тип контента')),
                ('menu_style', models.CharField(choices=[('horizontal_blocks', 'Горизонтальное меню (блоки)'), ('vertical_with_submenus', 'Вертикальное меню (с дочерними меню)'), ('vertical_without_submenus', 'Вертикальное меню (без дочерних меню)')], default='horizontal_blocks', max_length=64, verbose_name='Макет меню')),
                ('content_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.feed', verbose_name='Лента постов')),
                ('content_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.menu', verbose_name='Меню')),
                ('content_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Макет контента',
            },
        ),
        migrations.DeleteModel(
            name='ExtraContent',
        ),
    ]
