# Generated by Django 4.0.6 on 2022-07-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_extracontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracontent',
            old_name='menu',
            new_name='tied_to_menu',
        ),
    ]
